# Configuration
BINDIR = $(HOME)/bin
RNDROOT=$(HOME)/src/random
MODDIR=$(RNDROOT)/mod
Ver = 1



Rnd2dDir=$(RNDROOT)/2d
FFTDir=$(RNDROOT)/fft
NRDir=$(RNDROOT)/nr
MTDir=$(RNDROOT)/mt
ACFDir=$(RNDROOT)/acf
MISCDir=$(RNDROOT)/misc

VPATH=$(NRDir):$(FFTDir):$(MTDir):$(Rnd2dDir):$(MISCDir)

MAKE=make
ECHO=echo
RM=rm -f
F90=ifort
F77=ifort
F90FLAGS=-O3 -axW -xW -lsvml -assume byterecl
F77FLAGS=$(F90Flags)
OPTF90=-O3
OPTF77=-O3
LDFLAGS=-O3 -axW -xW -lsvml

